# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-FormBuilder-Plugin-Time-Piece
version:      0.1
version_from: lib/Class/DBI/FormBuilder/Plugin/Time/Piece.pm
installdirs:  site
requires:
    Class::DBI::FormBuilder:       0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
